name: Docker Image

on:
  push:
  schedule:
    - cron: '0 7 */2 * *'

env:
  DOCKERHUB_IMAGE_NAME: covid19pirat/pirat-frontend
  GITHUB_PACKAGES_IMAGE_NAME: docker.pkg.github.com/covid19-pirat/frontend/pirat-frontend
  IMAGE_TAG: latest
  BRANCH: NONE

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: write commit hash to file
        run: echo ${{ github.sha }} > src/assets/content/git_commit

      - name: set branch env
        run: |
          echo "::set-env name=BRANCH::${GITHUB_REF##*/}"

      - name: set tag to stable
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=IMAGE_TAG::stable"

      - name: set image tag to integration
        if: endsWith(github.ref, '/integration')
        run: |
          echo "::set-env name=IMAGE_TAG::integration"

      - name: set image tag to testing
        if: endsWith(github.ref, '/testing')
        run: |
          echo "::set-env name=IMAGE_TAG::testing"

      - name: build
        run: docker build -t frontend .

      - name: login to dockerhub
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: tag
        run: |
          docker tag frontend ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.sha }}
          docker tag frontend ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ env.BRANCH }}
          docker tag frontend ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker tag frontend ${{ env.DOCKERHUB_IMAGE_NAME }}:latest

      - name: push to dockerhub
        run: |
          docker push ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ env.BRANCH }}
          docker push ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKERHUB_IMAGE_NAME }}:latest

      - name: login to github packages
        run: docker login docker.pkg.github.com -u ${{ secrets.GITHUBPACKAGES_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: tag
        run: |
          docker tag frontend ${{ env.GITHUB_PACKAGES_IMAGE_NAME }}:${{ github.sha }}
          docker tag frontend ${{ env.GITHUB_PACKAGES_IMAGE_NAME }}:${{ env.BRANCH }}
          docker tag frontend ${{ env.GITHUB_PACKAGES_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker tag frontend ${{ env.GITHUB_PACKAGES_IMAGE_NAME }}:latest

      - name: push to github packages
        run: |
          docker push ${{ env.GITHUB_PACKAGES_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.GITHUB_PACKAGES_IMAGE_NAME }}:${{ env.BRANCH }}
          docker push ${{ env.GITHUB_PACKAGES_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.GITHUB_PACKAGES_IMAGE_NAME }}:latest

      - name: Slack notification
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: frontend
        with:
          args: "New Images available:\n- {{ GITHUB_SHA }}\n- {{ IMAGE_TAG }}\n- {{ BRANCH }}\n- latest"
